name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Navigate to the app directory
      run: cd pizza-ordering-app
    - name: Install dependencies
      run: npm ci
      working-directory: ./pizza-ordering-app
    - name: Build the project
      run: npm run build
      working-directory: ./pizza-ordering-app
      env:
        CI: true
